### ISSUE TITLE
bower old

### ISSUE THREAD

**Issue by agos1** [reactjs/react-bower#22] opened 2017-01-18 16:25 UTC
this bower format is old. it is not more possible to add multiple file with same extension.
You might use the bindep extension. 
npm bindep

**Comment by gaearon** [comment] 2017-06-15 14:36
Closing as part of cleanup. If this is still an issue please let us know.

**Comment by gaearon** [comment] 2017-06-15 14:36
(It's not clear to me what the problem is, this issue is not very descriptive. If there's something we need to do let us know.)

**Closed by gaearon** 2017-06-15 14:36 UTC
